name: document_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.10.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_mlkit_entity_extraction: ^0.15.1
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  image_editor_plus: ^1.0.6
  image_picker: ^1.1.1
  media_store_plus: ^0.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/frame.png
    - .env
